-- 循环1——n的和
DROP FUNCTION IF EXISTS sum3n;
CREATE PROCEDURE sum3n(n INT(11) ) RETURNS INT(11) COMMENT '循环1-n的和'
BEGIN
DECLARE i INT DEFAULT 1;
DECLARE s INT DEFAULT 0;
aa:LOOP
IF i > n THEN 
LEAVE aa;
END IF;
  SET s = s+i;
  SET i = i+1;
END LOOP;
SELECT s;
END